### ISSUE TITLE
Make form fields required

### ISSUE THREAD

**Issue by Sulpher** [PhocaCz/PhocaCart#1]
Hello Jan,

I noticed there is no way to make form fields required which is a must-have.
For instance, some payment services needs minimal billing information like region.
So, I am not able to make this field required and if users misses this param during the payment, they will not complete the payment due to error in data (no region).
Another example: site owner may want to make telephone as required param.
I also noticed there is no way to add custom field. Although, it is not necessary, but would be a good addition.

**Comment by PhocaCz** [comment]
Hi, thank you very much for the info, this is a design issue, the required select box is not displayed in administration of form fields, but it is there and required can be set for each field, I will fix it in next version

![Imgur](http://i.imgur.com/jsy4LVD.png)

Thank you, Jan

**Comment by PhocaCz** [comment]
Fixed in version 3.0.0 RC 7
