### ISSUE TITLE
Helix Ultimate (Bootstrap 5) - Module "Product module" issue

### ISSUE THREAD

**Issue by SamusUA** [PhocaCz/PhocaCart#115]
Template: Helix Ultimate 2.0.5 (JoomShaper.com) (very popular framework )
Template Layout: Bootstrap 5 (!)

ISSUES:
Module Product - Phoca Cart: Product сarousel not work. JS not work.

![image](https://user-images.githubusercontent.com/41996277/147969702-411b9ee4-3a36-483a-b80c-5ebd251fb244.png)

**Comment by SamusUA** [comment]
Sorry, I haven't figured out the functionality, it is very similar to a module with a carousel.

**Comment by PhocaCz** [comment]
Ok, BTW, there is even template override for Helix (Phoca Cart Cart module, Phoca Cart Wishlist module, Phoca Cart Currency module, Phoca Cart Compare module): 
https://www.phoca.cz/phocacart-extensions/5-overrides/43-overrides-helix
Jan

**Comment by SamusUA** [comment]
> Ok, BTW, there is even template override for Helix (Phoca Cart Cart module, Phoca Cart Wishlist module, Phoca Cart Currency module, Phoca Cart Compare module): https://www.phoca.cz/phocacart-extensions/5-overrides/43-overrides-helix Jan

Yes, I've tried all of these overrides. Unfortunately, they don't work as they should. No dropouts, no links. They are probably designed for Bootstrap 4. Helix 2.0.5 = Bootstrap 5.

**Comment by PhocaCz** [comment]
Hi, there are designed for Joomla 4, Bootstrap 5 and Helix version for Joomla 4

Phoca Cart options:
![001](https://i.imgur.com/tlQjEZ5.png)

Joomla 4 Helix Ultimate template:
![001](https://i.imgur.com/IROaxHD.png)

Set module position for Helix:
![img](https://i.imgur.com/9J7tVlc.png)

Module overrides displayed in Helix
![001](https://i.imgur.com/MpveEbP.png)

**Comment by SamusUA** [comment]
Yes, I understood everything, thanks!
But in the version of PhocaCart 3.5.8 there is no such functionality, and it is not yet possible to update to the version of Joomla 4.
Your answer is clear, the problem is the complexity of the update on my part.
Tell me: will it be possible in the future to easily update the PhocaCart component from version 3.5.8 to 4.0.0 ???

**Comment by PhocaCz** [comment]
>Tell me: will it be possible in the future to easily update the PhocaCart component from version 3.5.8 to 4.0.0

Really hard to say, but I have exported and imported data and files from Joomla 3 to Joomla 4, without any problem:
https://www.phoca.cz/phocacart4demo/
Used obsolete guide but still valid:
https://www.phoca.cz/documents/50-phoca/831-how-to-migrate-extensions-from-joomla-2-5-to-joomla-3 - upgrading from 2.5 to 3 is in fact the same like from 3 to 4 - it is about export/import

>Is it possible to use the entire PhocaCart 4.0 modules (with overrides) in the old version of Phoca Cart 3.5.8?
I didn't test it yet so hard to say. Joomla 3 and Joomla 4 are completely different systems but in case of overrides, there should not be so many changes there :idea:
