### ISSUE TITLE
Delivery and billing addresses are the same - small issue

### ISSUE THREAD

**Issue by Sulpher** [PhocaCz/PhocaCart#2]
I noticed a little issue with delivery and billing addresses.
Have a look at the screenshot:
![screen shot 2017-05-03 at 15 36 29](https://cloud.githubusercontent.com/assets/3432048/25660793/89b098bc-3016-11e7-8684-86d9439a9913.png)
Please take a look that "Delivery and billing addresses are the same" checkbox is enabled and second column with delivery address is inactive.

I click on "Save" and get the following result:
![screen shot 2017-05-03 at 15 36 59](https://cloud.githubusercontent.com/assets/3432048/25660829/b0a8f3e2-3016-11e7-9d15-dbca38ea60aa.png)

Shipping address should be the same as billing (according to enabled checkbox), but it displays values from billing address.

**Comment by PhocaCz** [comment]
Hi, thank you very much for the info, I will take a look at it.

Thank you, Jan

**Comment by PhocaCz** [comment]
Hi, fxed in version 3.0.0 RC7, thank you.
