### ISSUE TITLE
pHp error when adding Store Logo

### ISSUE THREAD

**Issue by geoffp-web** [PhocaCz/PhocaCart#237]
Options/Store/Store Logo

adding a .png or .gif to this field gives a pHp error 

0 Call to a member function parse() on null

Error fixed by deleting the Store Logo

Can you help please?

**Comment by geoffp-web** [comment]
nothing appears with logging enabled
---------------------------------
Also please how to enable the collection of customer mobile phone numbers in Online Store

**Comment by geoffp-web** [comment]
Found pHp error in Joomla logs

2024-07-06T01:46:12+00:00	CRITICAL 2a09:bac2:189:105::1a:dc	error	Uncaught Throwable of type Error thrown with message "Call to a member function parse() on null". Stack trace: #0 [internal function]: plgContentMavikThumbnails->imageReplacer()
#1 [ROOT]/plugins/content/mavikthumbnails/mavikthumbnails.php(157): preg_replace_callback()
#2 [ROOT]/libraries/src/Plugin/CMSPlugin.php(289): plgContentMavikThumbnails->onContentPrepare()

**Comment by PhocaCz** [comment]
Hi, in this case you need to contact the developer of the plugin mavikthumbnails to get information about the problem. :idea:
