### ISSUE TITLE
Problem checkout

### ISSUE THREAD

**Issue by Sa1ch** [PhocaCz/PhocaCart#6]
Hello! I have a problem. When you click the button "Order Confirmation" in the basket, a blank page appears at the address: /component/phocacart/checkout.html

In the admin area, if you open an order, an error appears:

> Fatal error: Call to a member function getValue() on boolean in /var/www/sites/data/www/site.ru/administrator/components/com_phocacart/libraries/phocacart/user/user.php on line 152
![1](https://user-images.githubusercontent.com/28288185/49274303-789d6a00-f4aa-11e8-85c4-3203027dacea.PNG)
![2](https://user-images.githubusercontent.com/28288185/49274304-789d6a00-f4aa-11e8-9936-9d07c386d89c.PNG)
![3](https://user-images.githubusercontent.com/28288185/49274305-79360080-f4aa-11e8-8414-aa6cd611f31c.PNG)

**Comment by PhocaCz** [comment]
Hi, which version of Phoca Cart do you run?

Jan

**Comment by Sa1ch** [comment]
Hey. I solved this problem. The fact is that I created the field "Country" in the form with the same name. And this field was removed in the table: cm_phocacart_order_users. I created it again and the problem was solved. thank

**Comment by PhocaCz** [comment]
Ok
