### ISSUE TITLE
Suggestion: "Product Added to shopping cart" message should have a cart link.

### ISSUE THREAD

**Issue by chetanmadaan** [PhocaCz/PhocaCart#7]
![image](https://user-images.githubusercontent.com/3968575/65353394-058ced80-dbbb-11e9-9853-530dc0ab614a.png)

Just like J2 store does. Because I haven't or don't want to publish the shopping cart module and it's hard to navigate to shopping cart or checkout.

**Comment by PhocaCz** [comment]
Hi,

you can set parameter: "Add To Cart Method" to "Ajax with popup window" value to get the links to "continue shopping" and "proceed to checkout"


![Phoca Cart Options](https://i.imgur.com/ChNhW1c.png)

So when you add a product to cart, popup will be displayed:

![Phoca Cart Popup - Add To Cart](https://i.imgur.com/HvG7DmD.png)

The window can be extended through the plugin, like displayed on the sreenshot - there is a plugin which displays image of the product and free shipping options.

As default it displays the message and the links (see JDSeattle example):

![Phoca Cart Popup - Add To Cart - standard](https://i.imgur.com/KByElvO.png)


BTW - in case you will use Phoca Cart Cart module, there are html overrides for JD/Astroid templates to download:

https://www.phoca.cz/phocacart-extensions/5-overrides/39-overrides-astroid

so you can display the modules at the top of the site:

![Phoca Cart modules - top](https://i.imgur.com/aAmWZd6.png)

**Comment by chetanmadaan** [comment]
Thanks for the very brief answer Jan. I think I just have to read and find documentation before posting here.

**Comment by PhocaCz** [comment]
Hi, no problem, this explanation can help other users, so it is OK.

**Comment by landed1** [comment]
Hi Where can I find the plugin or setting for the add to cart popup so it appears, I think above you said there was a plugin?

**Comment by PhocaCz** [comment]
Hi, there are two differen things:

1) Popup - this is a part of core and can be enabled in Phoca Cart Options, see: https://github.com/PhocaCz/PhocaCart/issues/7#issuecomment-533789124

2) Inside this popup, even a plugin can be rendered, in this case, it was: https://www.phoca.cz/phocacart-extensions/2-plugins/35-phoca-cart-free-shipping-info-plugin

Jan
