### ISSUE TITLE
Feature : Ability to Search Options.

### ISSUE THREAD

**Issue by chetanmadaan** [PhocaCz/PhocaCart#8]
Just like K2 did, PhocaCart has too many options (_which is very very useful_) but an ability to search through these options would be great.
![image](https://user-images.githubusercontent.com/3968575/65353672-b8f5e200-dbbb-11e9-9288-db4ac79e76a9.png)

I know Joomla by core doesn't provide this.

**Comment by PhocaCz** [comment]
Hi, yes, this is why there exists Phoca Filter Options System plugin:
 
https://www.phoca.cz/phoca-filter-options-system-plugin

![Phoca Filter Options System Plugin](https://i.imgur.com/dvauAdT.png)

You can even use it for all other components or global configuration

Joomla! 3
https://youtu.be/zKFdgqgbs1M

Joomla! 4
https://youtu.be/sn3bFggDdzI

**Comment by chetanmadaan** [comment]
This is great. Thank You!
