### ISSUE TITLE
Dropdowns on category view not working.

### ISSUE THREAD

**Issue by chetanmadaan** [PhocaCz/PhocaCart#9]
I have the settings similar to:
https://docs.joomdev.com/article/how-to-make-phocacart-astroid-blend-in-with-each-other/

See video here: https://www.dropbox.com/s/ezlrfp1r53npdhz/2019-09-20_15-32-40.mp4?dl=0

Dropdowns are find on product page but not on main category layout page.

Console doesn't have any errors.

**Comment by PhocaCz** [comment]
Hi,
first of all. Please go to:
media\com_phocacart\css\spec\astroid.css

and remove or comment everything below
/* Custom CSS */

(line cca 234)

This is an additional CSS which should not be a part of the file and will be removed in next version.

Back to problem: It seems like some Chosen vs. Bootstrap4/template conflict, so if you disable loading of Chosen, it should be OK:

![Phoca Cart Options - Load Chosen](https://i.imgur.com/u93SUrE.png)

![Phoca Cart - select box](https://i.imgur.com/BHOqFet.png)

Maybe you can update your documentation and add there the information that the 'Load Chosen' parameter should be even disabled. :idea:

**Comment by chetanmadaan** [comment]
Yup, disabling chosen fixes this.

I have updated the documentation to reflect the same:
https://docs.joomdev.com/article/how-to-make-phocacart-astroid-blend-in-with-each-other/

**Comment by PhocaCz** [comment]
Great to hear it.
